### **Predicting whether a customer will default on his/her credit card**

Made By - [Ranadip Manna](https://github.com/RanadipM/Machine_Learning_Projects.), [Yuvraj Sharma](https://github.com/uvee3t)

**Problem Description**

This project is aimed at predicting the case of customers default payments in Taiwan. From the perspective of risk management, the result of predictive accuracy of the estimated probability of default will be more valuable than the binary result of classification - credible or not credible clients.

**Data Description**

**Attribute Information**:

This research employed a binary variable, default payment (Yes = 1, No = 0), as the response variable.
This study reviewed the literature and used the following 23 variables as explanatory variables:

X1: Amount of the given credit (NT dollar): it includes both the individual consumer credit and his/her family (supplementary) credit.

X2: Gender (1 = male; 2 = female).

X3: Education (1 = graduate school; 2 = university; 3 = high school; 4 = others).

X4: Marital status (1 = married; 2 = single; 3 = others).

X5: Age (year).

X6 - X11: History of past payment. We tracked the past monthly payment records (from April to September, 2005) as follows: X6 = the repayment status in September, 2005; X7 = the repayment status in August, 2005; . . .;

X11 = the repayment status in April, 2005. The measurement scale for the repayment status is: -1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; . . .; 8 = payment delay for eight months; 9 = payment delay for nine months and above.

X12-X17: Amount of bill statement (NT dollar). X12 = amount of bill statement in September, 2005; X13 = amount of bill statement in August, 2005; . . .; X17 = amount of bill statement in April, 2005.

X18-X23: Amount of previous payment (NT dollar). X18 = amount paid in September, 2005; X19 = amount paid in August, 2005; . . .;X23 = amount paid in April, 2005.

**Features Description**

We have records of 30000 customers. Below are the description of all features:

ID: ID of each client

LIMIT_BAL: Amount of given credit in NT dollars (includes individual and family/supplementary credit

SEX: Gender (1=male, 2=female)

EDUCATION: (1=graduate school, 2=university, 3=high school, 4=others)

MARRIAGE: Marital status (1=married, 2=single, 3=others)

AGE: Age in years

PAY_0: Repayment status in September, 2005 (-1=pay duly, 1=payment delay for one month, 2=payment delay for two months,8=payment delay for eight months, 9=payment delay for nine months and above)

PAY_2: Repayment status in August, 2005 (scale same as above)

PAY_3: Repayment status in July, 2005 (scale same as above)

PAY_4: Repayment status in June, 2005 (scale same as above)

PAY_5: Repayment status in May, 2005 (scale same as above)

PAY_6: Repayment status in April, 2005 (scale same as above)

BILL_AMT1: Amount of bill statement in September, 2005 (NT dollar)

BILL_AMT2: Amount of bill statement in August, 2005 (NT dollar)

BILL_AMT3: Amount of bill statement in July, 2005 (NT dollar)

BILL_AMT4: Amount of bill statement in June, 2005 (NT dollar)

BILL_AMT5: Amount of bill statement in May, 2005 (NT dollar)

BILL_AMT6: Amount of bill statement in April, 2005 (NT dollar)

PAY_AMT1: Amount of previous payment in September, 2005 (NT dollar)

PAY_AMT2: Amount of previous payment in August, 2005 (NT dollar)

PAY_AMT3: Amount of previous payment in July, 2005 (NT dollar)

PAY_AMT4: Amount of previous payment in June, 2005 (NT dollar)

PAY_AMT5: Amount of previous payment in May, 2005 (NT dollar)

PAY_AMT6: Amount of previous payment in April, 2005 (NT dollar)
default.payment.next.month: Default payment (1=yes, 0=no)

In [ ]:
#Importing Models
import numpy as np
import pandas as pd
import plotly.express as px
from sklearn.model_selection import (train_test_split, StratifiedKFold, GridSearchCV, cross_validate, cross_val_score)
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import ConfusionMatrixDisplay, RocCurveDisplay, PrecisionRecallDisplay
import joblib
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.metrics import confusion_matrix, roc_auc_score, classification_report

In [ ]:
#File Upload
from google.colab import files
uploaded = files.upload()
for filename in uploaded.keys():
  print(filename)

Saving default of credit card clients use excl.xls to default of credit card clients use excl (1).xls
default of credit card clients use excl (1).xls

In [ ]:
# Read the uploaded Excel file using pd.read_excel
df = pd.read_excel('default of credit card clients use excl.xls')
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [ ]:
# Check shape of dataset
df.shape

(30000, 25)

In [ ]:
# Checking last 5 rows in dataset
df.tail()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
29995,29996,220000,1,3,1,39,0,0,0,0,...,88004,31237,15980,8500,20000,5003,3047,5000,1000,0
29996,29997,150000,1,3,2,43,-1,-1,-1,-1,...,8979,5190,0,1837,3526,8998,129,0,0,0
29997,29998,30000,1,2,2,37,4,3,2,-1,...,20878,20582,19357,0,0,22000,4200,2000,3100,1
29998,29999,80000,1,3,1,41,1,-1,0,0,...,52774,11855,48944,85900,3409,1178,1926,52964,1804,1
29999,30000,50000,1,2,1,46,0,0,0,0,...,36535,32428,15313,2078,1800,1430,1000,1000,1000,1

In [ ]:
# Checking basic information of our dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_AMT3                   30000 non-null  int64
 15  BILL_AMT4                   30000 non-null  int64
 16  BILL_AMT5                   30000 non-null  int64
 17  BILL_AMT6                   30000 non-null  int64
 18  PAY_AMT1                    30000 non-null  int64
 19  PAY_AMT2                    30000 non-null  int64
 20  PAY_AMT3                    30000 non-null  int64
 21  PAY_AMT4                    30000 non-null  int64
 22  PAY_AMT5                    30000 non-null  int64
 23  PAY_AMT6                    30000 non-null  int64
 24  default payment next month  30000 non-null  int64
dtypes: int64(25)
memory usage: 5.7 MB

In [ ]:
# Exploring descriptive statistical parameters
df.describe()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000,30000.000000
mean,15000.500000,167484.322667,1.603733,1.853133,1.551867,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,...,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567,0.221200
std,8660.398374,129747.661567,0.489129,0.790349,0.521970,9.217904,1.123802,1.197186,1.196868,1.169139,...,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775,0.415062
min,1.000000,10000.000000,1.000000,0.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000
25%,7500.750000,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000,0.000000
50%,15000.500000,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,...,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000,0.000000
75%,22500.250000,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,...,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000,0.000000
max,30000.000000,1000000.000000,2.000000,6.000000,3.000000,79.000000,8.000000,8.000000,8.000000,8.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000,1.000000

In [ ]:
# checking the total number of null values in every column
df.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

In [ ]:
# checking for identical rows if present
df.duplicated().sum()

np.int64(0)

In [ ]:
# Rename the columns
df = df.rename(columns={'default payment next month': 'DEFAULT_PAYMENT','PAY_0': 'PAY_1'})
df.head(2)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT_PAYMENT
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1

**Exploratory Data Anlaysis**

Class Imbalance Check

In [ ]:
#Count
df = pd.read_excel('default of credit card clients use excl.xls')
df = df.rename(columns={'default payment next month': 'DEFAULT_PAYMENT'})
counts = df['DEFAULT_PAYMENT'].value_counts()
print(counts)

DEFAULT_PAYMENT
0    23364
1     6636
Name: count, dtype: int64

In [ ]:
#Graphical Representation of Count
fig = px.bar(counts,
    x=counts.index,
    y=counts.values,
    labels={'x': 'DEFAULT_PAYMENT', 'y': 'Count'},
    title='Default Credit Card Clients (1 = Default, 0 = Not Default)'
)

fig.show()

Defaulters are less as compared to the Non-Defaulters in the given dataset.

In [ ]:
#Count
independent_variable = ['SEX', 'EDUCATION', 'MARRIAGE', 'AGE']
for col in independent_variable :
  print(df[col].value_counts())

SEX
2    18112
1    11888
Name: count, dtype: int64
EDUCATION
2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: count, dtype: int64
MARRIAGE
2    15964
1    13659
3      323
0       54
Name: count, dtype: int64
AGE
29    1605
27    1477
28    1409
30    1395
26    1256
31    1217
25    1186
34    1162
32    1158
33    1146
24    1127
35    1113
36    1108
37    1041
39     954
38     944
23     931
40     870
41     824
42     794
44     700
43     670
45     617
46     570
22     560
47     501
48     466
49     452
50     411
51     340
53     325
52     304
54     247
55     209
56     178
57     122
58     122
59      83
21      67
60      67
61      56
62      44
64      31
63      31
66      25
65      24
67      16
69      15
70      10
68       5
73       4
75       3
71       3
72       3
79       1
74       1
Name: count, dtype: int64

In [ ]:
# Replacing the value as according to feature description
df["EDUCATION"] = df["EDUCATION"].replace({0:4,5:4,6:4})
df["MARRIAGE"] = df["MARRIAGE"].replace({0:3})

In [ ]:
# Value counts after replacing of "EDUCATION", "MARRIAGE"
print(df['EDUCATION'].value_counts())
print(df['MARRIAGE'].value_counts())

EDUCATION
2    14030
1    10585
3     4917
4      468
Name: count, dtype: int64
MARRIAGE
2    15964
1    13659
3      377
Name: count, dtype: int64

In [ ]:
#Graphical Representation
for col in independent_variable:
    if col == 'AGE':
        fig = px.histogram(df, x=col, nbins=20, title=f'Distribution of {col.upper()}')
    else:
        counts_for_col = df[col].value_counts().reset_index()
        counts_for_col.columns = [col, 'Count']
        fig = px.bar(
            counts_for_col,
            x=col,
            y='Count',
            title=f'Count vs {col.upper()}',
            text_auto=True )
    fig.update_layout(width=800, height=450)
    fig.show()

In [ ]:
# Creating a box plot of AGE V/S DEFAULT_PAYMENT with respect to sex
px.box(df, x='DEFAULT_PAYMENT', color='SEX', y='AGE' ,width=900,
    height=500)

In [ ]:
# Creating a box plot of AGE V/S DEFAULT_PAYMENT with respect to marriage
px.box(df,x='DEFAULT_PAYMENT',color='MARRIAGE', y='AGE', width=900,
    height=500)

In [ ]:
# Creating a box plot of AGE V/S DEFAULT_PAYMENT with respect to education
px.box(df,x='DEFAULT_PAYMENT',color='EDUCATION', y='AGE', width=900,
    height=500)

In [ ]:
# Creating a function to get columnn names in the given range.
def getColumnsNames(pxp):
  return [pxp+str(x) for x in range(1,7)]

In [ ]:
#Graphical Representation
pay_columns = ['PAY_1', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']
for col in pay_columns:
    fig = px.histogram(
        df,
        x=col,
        color='DEFAULT_PAYMENT',
        barmode='group',
        title=f"{col} — Default (1) vs Non-default (0)",
    )
    fig.update_layout(width=800, height=450)
    fig.show()

In [ ]:
#Graphical Representation
fig = px.box(
    df,
    x='DEFAULT',
    y='LIMIT_BAL',
    color='DEFAULT',
    title='Credit Limit Distribution by Default Status',
    labels={'DEFAULT': 'Default Status (0: No, 1: Yes)', 'LIMIT_BAL': 'Limit Balance Amount'},
    color_discrete_map={'0.0': 'skyblue', '1.0': 'salmon'}
)
fig.update_layout(yaxis_type="log")
fig.show()

The above figures show The default status for the various predictors

**Correlation**

In [ ]:
# Dropping the column "ID"
df = df.drop(['ID'],axis=1)

In [ ]:
#Graphical Representation
bill_pay_cols = [col for col in df.columns if 'BILL_AMT' in col or 'PAY_AMT' in col]
corr_matrix = df[bill_pay_cols].corr()

fig = px.imshow(
    corr_matrix,
    text_auto=True,
    aspect="auto",
    color_continuous_scale=px.colors.diverging.RdYlGn,
    title='Correlation Matrix of Monthly Bill and Payment Amounts',
    labels={'color': 'Correlation', 'x': 'Feature', 'y': 'Feature'}
)
fig.update_xaxes(side="top")
fig.show()

In [ ]:
#Graphical Representation
corr_matrix = df.corr()
fig = px.imshow(
    corr_matrix,color_continuous_scale='RdBu',text_auto=True)
fig.update_layout(width=1500, height=1200)
fig.show()

The heat map shows the features which are the most coreelated with the target variable Pay_1 ,Pay_2,Limit_bal ,Pay_3,Pay_4,Pay_5,Pay_6.

In [ ]:
# Correlation between independent variables and dependent variable.
X = df.drop(['DEFAULT_PAYMENT'], axis=1)
corr_values = X.corrwith(df['DEFAULT_PAYMENT'])
corr_df = corr_values.reset_index()
corr_df.columns = ['Variable', 'Correlation']

In [ ]:
fig = px.bar(
    corr_df,
    x='Variable',
    y='Correlation',
    title='Correlation with DEFAULT_PAYMENT',
)
fig.show()

The bar chart also shows the features which are the most correlated with the target variable Pay_1 ,Pay_2,Limit_bal ,Pay_3,Pay_4,Pay_5,Pay_6.It seems from the above graph is LIMIT_BAL is that most negatively correlated feature.

**SMOTE (Synthetic Minority Oversampling Technique)**

In [ ]:
# Importing SMOTE
from imblearn.over_sampling import SMOTE
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Creating a SMOTE function.
smote = SMOTE()

x_smote, y_smote = smote.fit_resample(X, df['DEFAULT_PAYMENT'])

print('Original shape of Dataset', len(X))
print('Resampled shape of Dataset', len(y_smote))

Original shape of Dataset 30000
Resampled shape of Dataset 46728

In [ ]:
# Creating a new dataframe after using SMOTE
balance_df = pd.DataFrame(x_smote, columns = list(X.columns))
balance_df['DEFAULT_PAYMENT'] = y_smote

In [ ]:
# Creating a count plot for "DEFAULT_PAYMENT"
default_payment_counts = balance_df['DEFAULT_PAYMENT'].value_counts().reset_index()
default_payment_counts.columns = ['DEFAULT_PAYMENT', 'Count']

fig = px.bar(
    default_payment_counts,
    x='DEFAULT_PAYMENT',
    y='Count',
    title='Default Credit Card Clients (1 = Default, 0 = Not Default)',
    text_auto=True
)
fig.show()

In [ ]:
balance_df[balance_df['DEFAULT_PAYMENT']==1]

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT_PAYMENT
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
13,70000,1,2,2,30,1,2,2,0,0,...,66782,36137,36894,3200,0,3000,3000,1500,0,1
16,20000,1,1,2,24,0,0,2,2,2,...,18338,17905,19104,3200,0,1500,0,1650,0,1
21,120000,2,2,1,39,-1,-1,-1,-1,-1,...,0,632,316,316,316,0,632,316,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46723,140000,2,1,2,26,-1,0,0,0,0,...,4530,4338,1159,2000,1694,2220,1565,38,2980,1
46724,90000,2,1,2,26,0,0,0,0,0,...,82927,83328,86375,4737,3881,3074,2372,4849,2655,1
46725,80000,2,2,1,28,2,0,0,2,0,...,22094,21773,21767,3109,5036,0,666,680,2810,1
46726,199243,1,1,1,42,0,0,0,0,0,...,72170,71927,73855,3962,3894,4818,2569,4822,4848,1
46727,134146,1,1,1,28,2,1,1,-2,-2,...,0,0,0,286,0,0,0,0,0,1

In [ ]:
x_train_sm, x_test_sm, y_train_sm, y_test_sm = train_test_split(x_smote,y_smote, test_size = 0.2, random_state = 24,stratify = y_smote)

**Feature Engineering**

In [ ]:
# Creating a dummy copy of our dataset
df_0= balance_df.copy()

In [ ]:
# Bin ‘AGE’ data to 6 groups
bins= [20,30,40,50,60,70,80]
labels = list(range(6))
df_0['AGE'] = pd.cut(df_0['AGE'],bins=bins, labels=labels,right=False)

In [ ]:
# Covert categorical column into integer by extracting the code of the categories
df_0['AGE'] = df_0['AGE'].astype('float64').fillna(-1).astype('int64')

In [ ]:
df_0.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT_PAYMENT
0,20000,2,2,1,0,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,0,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,1,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,1,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,3,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [ ]:
# Define predictor variables and target variable
X = df_0.drop(columns=['DEFAULT_PAYMENT'])
y = df_0['DEFAULT_PAYMENT']

# Save all feature names as list
feature_cols = X.columns.tolist()

In [ ]:
# Extract numerical columns and save as a list for rescaling
X_num = X.drop(columns=['SEX', 'EDUCATION', 'MARRIAGE', 'AGE'])
num_cols = X_num.columns.tolist()

In [ ]:
# Define function to split data
def data_split(X, y):
   X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)
   return X_train, X_test, y_train, y_test

In [ ]:
 #Define function to rescale training data using StandardScaler

def standard_scaler(X_train, X_test, numerical_cols):

  # Make copies of dataset
  X_train_std = X_train.copy()
  X_test_std = X_test.copy()

  # Apply standardization on numerical features only
  for i in numerical_cols:
    scl = StandardScaler().fit(X_train_std[[i]])
    X_train_std[i] = scl.transform(X_train_std[[i]])
    X_test_std[i] = scl.transform(X_test_std[[i]])

  return X_train_std,X_test_std

**Logistic Regression**

In [ ]:
#1)split
X_train, X_test, y_train, y_test = data_split(X, y)

In [ ]:
#2)derive categorical columns
categorical_cols = [c for c in X.columns if c not in num_cols]

In [ ]:
#3 Building Preprocessors
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [ ]:
categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

In [ ]:
preprocessor = ColumnTransformer(transformers=[
    ("num", numeric_transformer, num_cols),
    ("cat", categorical_transformer, categorical_cols)
], remainder="drop")

In [ ]:
#4)Build imblearn pipeline: preprocessor
pipeline = ImbPipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote", SMOTE(random_state=42)),
    ("classifier", LogisticRegression(solver="liblinear", random_state=42))
])

In [ ]:
# 5) Cross-validated baseline
cv_scores = cross_val_score(pipeline, X_train, y_train, scoring="roc_auc", cv=5, n_jobs=-1)
print("Pipeline CV ROC_AUC (with SMOTE inside folds):", np.mean(cv_scores).round(4))

Pipeline CV ROC_AUC (with SMOTE inside folds): 0.7937

In [ ]:
# 6) GridSearchCV for hyperparameters
param_grid = {
    "classifier__C": [0.001, 0.01, 0.1, 1, 10],
    "classifier__penalty": ["l2"]
}

gs = GridSearchCV(pipeline, param_grid, scoring="roc_auc", cv=3, n_jobs=-1, verbose=1)
gs.fit(X_train, y_train)

Fitting 3 folds for each of 5 candidates, totalling 15 fits

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['LIMIT_BAL',
                                                                          'PAY_1',
                                                                          'PAY_2',
                                                                          'PAY_3',
                                                                          'PAY_4',
                                                                          'PAY_5',
                                                                          'PAY_6',
                                                                          'BILL_AMT1',
                                                                          'BILL_AMT2',
                                                                          'BILL_AMT3',
                                                                          'BILL_AMT4',
                                                                          'BILL_AMT5',
                                                                          'BILL_AMT6',
                                                                          'PAY_AMT1',
                                                                          'PAY_AMT2',
                                                                          'PAY_...
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('onehot',
                                                                                          OneHotEncoder(handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         ['SEX',
                                                                          'EDUCATION',
                                                                          'MARRIAGE',
                                                                          'AGE'])])),
                                       ('smote', SMOTE(random_state=42)),
                                       ('classifier',
                                        LogisticRegression(random_state=42,
                                                           solver='liblinear'))]),
             n_jobs=-1,
             param_grid={'classifier__C': [0.001, 0.01, 0.1, 1, 10],
                         'classifier__penalty': ['l2']},
             scoring='roc_auc', verbose=1)

In [ ]:
print("GridSearch best params:", gs.best_params_)
best_pipeline = gs.best_estimator_

GridSearch best params: {'classifier__C': 10, 'classifier__penalty': 'l2'}

In [ ]:
# 7) Evaluate the best pipeline on held-out test set
y_pred = best_pipeline.predict(X_test)
y_proba = best_pipeline.predict_proba(X_test)[:, 1]

In [ ]:
# 8) Compute and print metricsfrom sklearn.metrics
import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report, confusion_matrix

accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall    = recall_score(y_test, y_pred)
f1        = f1_score(y_test, y_pred)
roc_auc   = roc_auc_score(y_test, y_proba)

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

print("\nModel Performance Metrics:")
print("Accuracy :", round(accuracy,4))
print("Precision:", round(precision,4))
print("Recall   :", round(recall,4))
print("F1 Score :", round(f1,4))
print("ROC AUC  :", round(roc_auc,4))
print("Test ROC_AUC:", round(roc_auc_score(y_test, y_proba), 4))
print("\nClassification report (test):\n", classification_report(y_test, y_pred))
print("Confusion Matrix -> TN:", tn, "FP:", fp, "FN:", fn, "TP:", tp)

Model Performance Metrics:
Accuracy : 0.7207
Precision: 0.716
Recall   : 0.7315
F1 Score : 0.7236
ROC AUC  : 0.795
Test ROC_AUC: 0.795

Classification report (test):
               precision    recall  f1-score   support

           0       0.73      0.71      0.72      7010
           1       0.72      0.73      0.72      7009

    accuracy                           0.72     14019
   macro avg       0.72      0.72      0.72     14019
weighted avg       0.72      0.72      0.72     14019

Confusion Matrix -> TN: 4976 FP: 2034 FN: 1882 TP: 5127

In [ ]:
from sklearn.metrics import confusion_matrix
import plotly.figure_factory as ff

# Logistic Regression
y_pred_logreg = best_pipeline.predict(X_test)
cm_logreg = confusion_matrix(y_test, y_pred_logreg)

fig_logreg = ff.create_annotated_heatmap(
    z=cm_logreg,
    x=['Predicted 0', 'Predicted 1'],
    y=['Actual 0', 'Actual 1'],
    colorscale='twilight',
    showscale=True
)
fig_logreg.update_layout(title='Logistic Regression Confusion Matrix')
fig_logreg.show()

In [ ]:
# 9) Save the entire pipeline (preprocessor + smote + classifier)
joblib.dump(best_pipeline, "logreg_imblearn_pipeline_with_smote.joblib")
print("Saved pipeline artifact -> logreg_imblearn_pipeline_with_smote.joblib")

Saved pipeline artifact -> logreg_imblearn_pipeline_with_smote.joblib

KNN

In [ ]:
# 1) split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# 2) derive categorical columns
categorical_cols = [c for c in X.columns if c not in num_cols]

In [ ]:
# 3) Build preprocessors
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocessor = ColumnTransformer(transformers=[
    ("num", numeric_transformer, num_cols),
    ("cat", categorical_transformer, categorical_cols)
], remainder="drop")

In [ ]:
# 4) Build imblearn pipeline: preprocessor -> SMOTE -> KNN classifier
pipeline_knn = ImbPipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote", SMOTE(random_state=42)),
    ("classifier", KNeighborsClassifier())
])

In [ ]:
# 5) Cross-validated baseline
cv_scores_knn = cross_val_score(pipeline_knn, X_train, y_train, scoring="roc_auc", cv=5, n_jobs=-1)
print("KNN Pipeline CV ROC_AUC (with SMOTE inside folds):", np.mean(cv_scores_knn).round(4))

KNN Pipeline CV ROC_AUC (with SMOTE inside folds): 0.8162

In [ ]:
# 6) GridSearchCV for KNN hyperparameters
param_grid_knn = {
    "classifier__n_neighbors": [3, 5, 7, 9, 11],
    "classifier__weights": ["uniform", "distance"],
    "classifier__p": [1, 2]  # p=1 -> Manhattan, p=2 -> Euclidean
}

gs_knn = GridSearchCV(pipeline_knn, param_grid_knn, scoring="roc_auc", cv=3, n_jobs=-1, verbose=1)
gs_knn.fit(X_train, y_train)

print("Best KNN params:", gs_knn.best_params_)
best_knn_pipeline = gs_knn.best_estimator_

Fitting 3 folds for each of 20 candidates, totalling 60 fits
Best KNN params: {'classifier__n_neighbors': 11, 'classifier__p': 1, 'classifier__weights': 'distance'}

In [ ]:
# 7) Fit best pipeline on full training set (GridSearch already fitted it but safe to call fit again)
best_knn_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['LIMIT_BAL', 'PAY_1',
                                                   'PAY_2', 'PAY_3', 'PAY_4',
                                                   'PAY_5', 'PAY_6',
                                                   'BILL_AMT1', 'BILL_AMT2',
                                                   'BILL_AMT3', 'BILL_AMT4',
                                                   'BILL_AMT5', 'BILL_AMT6',
                                                   'PAY_AMT1', 'PAY_AMT2',
                                                   'PAY_AMT3', 'PAY_AMT4',
                                                   'PAY_AMT5', 'PAY_AMT6']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['SEX', 'EDUCATION',
                                                   'MARRIAGE', 'AGE'])])),
                ('smote', SMOTE(random_state=42)),
                ('classifier',
                 KNeighborsClassifier(n_neighbors=11, p=1,
                                      weights='distance'))])

In [ ]:
# 8) Predict on held-out test set
y_pred = best_knn_pipeline.predict(X_test)
# KNN supports predict_proba
y_proba = best_knn_pipeline.predict_proba(X_test)[:, 1]

In [ ]:
# 9) Compute and print metrics
accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall    = recall_score(y_test, y_pred)
f1        = f1_score(y_test, y_pred)
roc_auc   = roc_auc_score(y_test, y_proba)

print("\nKNN Model Performance Metrics:")
print("Accuracy :", round(accuracy,4))
print("Precision:", round(precision,4))
print("Recall   :", round(recall,4))
print("F1 Score :", round(f1,4))
print("ROC AUC  :", round(roc_auc,4))
print("\nClassification Report (test):\n", classification_report(y_test, y_pred))
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print("Confusion Matrix -> TN:", tn, "FP:", fp, "FN:", fn, "TP:", tp)

KNN Model Performance Metrics:
Accuracy : 0.7873
Precision: 0.7643
Recall   : 0.8307
F1 Score : 0.7961
ROC AUC  : 0.8697

Classification Report (test):
               precision    recall  f1-score   support

           0       0.81      0.74      0.78      4673
           1       0.76      0.83      0.80      4673

    accuracy                           0.79      9346
   macro avg       0.79      0.79      0.79      9346
weighted avg       0.79      0.79      0.79      9346

Confusion Matrix -> TN: 3476 FP: 1197 FN: 791 TP: 3882

In [ ]:
from sklearn.metrics import confusion_matrix
import plotly.figure_factory as ff

# KNN
y_pred_knn = best_knn_pipeline.predict(X_test)
cm_knn = confusion_matrix(y_test, y_pred_knn)

fig_knn = ff.create_annotated_heatmap(
    z=cm_knn,
    x=['Predicted 0', 'Predicted 1'],
    y=['Actual 0', 'Actual 1'],
    colorscale='sunsetdark',
    showscale=True
)
fig_knn.update_layout(title='KNN Confusion Matrix')
fig_knn.show()

In [ ]:
joblib.dump(best_knn_pipeline, "knn_imblearn_pipeline_with_smote.joblib")
print("Saved -> knn_imblearn_pipeline_with_smote.joblib")

Saved -> knn_imblearn_pipeline_with_smote.joblib

**Decision Tree Classifier**

Decision trees and ensemble methods do not require feature scaling to be performed as they are not sensitive to the the variance in the data. So here we will use X_train,X_test,y_test and Y_train which are not scaled.

In [ ]:
# 1) split
X_train, X_test, y_train, y_test = data_split(X, y)

In [ ]:
# 2) derive categorical columns
categorical_cols = [c for c in X.columns if c not in num_cols]

In [ ]:
# 3) preprocessors
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("ohe", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocessor = ColumnTransformer(transformers=[
    ("num", numeric_transformer, num_cols),
    ("cat", categorical_transformer, categorical_cols)
], remainder="drop")

In [ ]:
# 4)Decision Tree pipeline
pipeline_dt = ImbPipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote", SMOTE(random_state=42)),
    ("classifier", DecisionTreeClassifier(random_state=42))
])

In [ ]:
# 5) CV baseline
cv_scores_dt = cross_val_score(pipeline_dt, X_train, y_train, scoring="roc_auc", cv=5, n_jobs=-1)
print("Decision Tree CV ROC_AUC:", np.mean(cv_scores_dt).round(4))

Decision Tree CV ROC_AUC: 0.7408

In [ ]:
# 6) GridSearch
param_grid_dt = {
    "classifier__max_depth": [3, 5, 7, 9, None],
    "classifier__min_samples_split": [2, 5, 10],
    "classifier__min_samples_leaf": [1, 2, 4]
}

gs_dt = GridSearchCV(pipeline_dt, param_grid_dt, scoring="roc_auc", cv=3, n_jobs=-1, verbose=1)
gs_dt.fit(X_train, y_train)

print("Best DT params:", gs_dt.best_params_)
best_dt_pipeline = gs_dt.best_estimator_

Fitting 3 folds for each of 45 candidates, totalling 135 fits
Best DT params: {'classifier__max_depth': 9, 'classifier__min_samples_leaf': 4, 'classifier__min_samples_split': 10}

In [ ]:
# 7) Fit best pipeline on full training set
best_dt_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['LIMIT_BAL', 'PAY_1',
                                                   'PAY_2', 'PAY_3', 'PAY_4',
                                                   'PAY_5', 'PAY_6',
                                                   'BILL_AMT1', 'BILL_AMT2',
                                                   'BILL_AMT3', 'BILL_AMT4',
                                                   'BILL_AMT5', 'BILL_AMT6',
                                                   'PAY_AMT1', 'PAY_AMT2',
                                                   'PAY_AMT3', 'PAY_AMT4',
                                                   'PAY_AMT5', 'PAY_AMT6']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ohe',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['SEX', 'EDUCATION',
                                                   'MARRIAGE', 'AGE'])])),
                ('smote', SMOTE(random_state=42)),
                ('classifier',
                 DecisionTreeClassifier(max_depth=9, min_samples_leaf=4,
                                        min_samples_split=10,
                                        random_state=42))])

In [ ]:
# 7) Predictions
y_pred = best_dt_pipeline.predict(X_test)
y_proba = best_dt_pipeline.predict_proba(X_test)[:, 1]

accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall    = recall_score(y_test, y_pred)
f1        = f1_score(y_test, y_pred)
roc_auc   = roc_auc_score(y_test, y_proba)

print("\nDecision Tree Performance Metrics:")
print("Accuracy :", round(accuracy,4))
print("Precision:", round(precision,4))
print("Recall   :", round(recall,4))
print("F1 Score :", round(f1,4))
print("ROC AUC  :", round(roc_auc,4))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix -> TN:", tn, "FP:", fp, "FN:", fn, "TP:", tp)

Decision Tree Performance Metrics:
Accuracy : 0.7462
Precision: 0.759
Recall   : 0.7214
F1 Score : 0.7397
ROC AUC  : 0.8167

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.77      0.75      7010
           1       0.76      0.72      0.74      7009

    accuracy                           0.75     14019
   macro avg       0.75      0.75      0.75     14019
weighted avg       0.75      0.75      0.75     14019

Confusion Matrix -> TN: 3476 FP: 1197 FN: 791 TP: 3882

In [ ]:
from sklearn.metrics import confusion_matrix
import plotly.figure_factory as ff

# Decision Tree
y_pred_dt = best_dt_pipeline.predict(X_test)
cm_dt = confusion_matrix(y_test, y_pred_dt)

fig_dt = ff.create_annotated_heatmap(
    z=cm_dt,
    x=['Predicted 0', 'Predicted 1'],
    y=['Actual 0', 'Actual 1'],
    colorscale='delta',
    showscale=True
)
fig_dt.update_layout(title='Decision Tree Confusion Matrix')
fig_dt.show()

In [ ]:
# 8) save
joblib.dump(best_dt_pipeline, "decision_tree_pipeline.joblib")
print("Saved -> decision_tree_pipeline.joblib")

Saved -> decision_tree_pipeline.joblib

Random Forest

In [ ]:
#1)split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
#2)derive categorical column
categorical_cols = [c for c in X.columns if c not in num_cols]

In [ ]:
# 3) build preprocessors
# Random Forest is not scale-sensitive, but we keep the same preprocessing pattern for consistency.
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocessor = ColumnTransformer(transformers=[
    ("num", numeric_transformer, num_cols),
    ("cat", categorical_transformer, categorical_cols)
], remainder="drop")

In [ ]:
#4) build imblearn pipeline:
pipeline_rf = ImbPipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote", SMOTE(random_state=42)),
    ("classifier", RandomForestClassifier(random_state=42, n_jobs=-1))
])

In [ ]:
# 5) quick CV baseline (SMOTE + preprocess applied inside folds)
cv_scores_rf = cross_val_score(pipeline_rf, X_train, y_train, scoring="roc_auc", cv=5, n_jobs=-1)
print("Random Forest Pipeline CV ROC_AUC (with SMOTE inside folds):", np.mean(cv_scores_rf).round(4))

Random Forest Pipeline CV ROC_AUC (with SMOTE inside folds): 0.9026

In [ ]:
# 6) GridSearchCV for Random Forest hyperparameters
param_grid_rf = {
    "classifier__n_estimators": [100, 200],
    "classifier__max_depth": [None, 6, 10, 15],
    "classifier__min_samples_leaf": [1, 2, 5],
}

gs_rf = GridSearchCV(pipeline_rf, param_grid_rf, scoring="roc_auc", cv=3, n_jobs=-1, verbose=1)
gs_rf.fit(X_train, y_train)

print("Best RF params:", gs_rf.best_params_)
best_rf_pipeline = gs_rf.best_estimator_

Fitting 3 folds for each of 24 candidates, totalling 72 fits
Best RF params: {'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__n_estimators': 200}

In [ ]:
# 7) Fit best pipeline on full training set
best_rf_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['LIMIT_BAL', 'PAY_1',
                                                   'PAY_2', 'PAY_3', 'PAY_4',
                                                   'PAY_5', 'PAY_6',
                                                   'BILL_AMT1', 'BILL_AMT2',
                                                   'BILL_AMT3', 'BILL_AMT4',
                                                   'BILL_AMT5', 'BILL_AMT6',
                                                   'PAY_AMT1', 'PAY_AMT2',
                                                   'PAY_AMT3', 'PAY_AMT4',
                                                   'PAY_AMT5', 'PAY_AMT6']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['SEX', 'EDUCATION',
                                                   'MARRIAGE', 'AGE'])])),
                ('smote', SMOTE(random_state=42)),
                ('classifier',
                 RandomForestClassifier(n_estimators=200, n_jobs=-1,
                                        random_state=42))])

In [ ]:
# 8) Predict on held-out test set
y_pred = best_rf_pipeline.predict(X_test)
# RandomForest supports predict_proba
y_proba = best_rf_pipeline.predict_proba(X_test)[:, 1]

In [ ]:
# 9) Compute & print metrics
accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall    = recall_score(y_test, y_pred)
f1        = f1_score(y_test, y_pred)
roc_auc   = roc_auc_score(y_test, y_proba)

print("\nRandom Forest Model Performance Metrics:")
print("Accuracy :", round(accuracy,4))
print("Precision:", round(precision,4))
print("Recall   :", round(recall,4))
print("F1 Score :", round(f1,4))
print("ROC AUC  :", round(roc_auc,4))
print("\nClassification Report (test):\n", classification_report(y_test, y_pred))
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print("Confusion Matrix -> TN:", tn, "FP:", fp, "FN:", fn, "TP:", tp)

Random Forest Model Performance Metrics:
Accuracy : 0.8369
Precision: 0.8467
Recall   : 0.8228
F1 Score : 0.8346
ROC AUC  : 0.9116

Classification Report (test):
               precision    recall  f1-score   support

           0       0.83      0.85      0.84      4673
           1       0.85      0.82      0.83      4673

    accuracy                           0.84      9346
   macro avg       0.84      0.84      0.84      9346
weighted avg       0.84      0.84      0.84      9346

Confusion Matrix -> TN: 3977 FP: 696 FN: 828 TP: 3845

In [ ]:
from sklearn.metrics import confusion_matrix
import plotly.figure_factory as ff

# Random Forest
y_pred_rf = best_rf_pipeline.predict(X_test)
cm_rf = confusion_matrix(y_test, y_pred_rf)

fig_rf = ff.create_annotated_heatmap(
    z=cm_rf,
    x=['Predicted 0', 'Predicted 1'],
    y=['Actual 0', 'Actual 1'],
    colorscale='darkmint',
    showscale=True
)
fig_rf.update_layout(title='Random Forest Confusion Matrix')
fig_rf.show()

In [ ]:
#save
joblib.dump(best_rf_pipeline, "random_forest_imblearn_pipeline_with_smote.joblib")
print("Saved -> random_forest_imblearn_pipeline_with_smote.joblib")

Saved -> random_forest_imblearn_pipeline_with_smote.joblib

In [ ]:
from IPython.display import display

# Compile the results of all models
results = pd.DataFrame({
    'Model': ['Logistic Regression', 'KNN', 'Decision Tree', 'Random Forest'],
    'Accuracy': [0.7899, 0.7899, 0.7479, 0.8428],
    'Precision': [0.7661, 0.7661, 0.7771, 0.8480],
    'Recall': [0.8346, 0.8346, 0.6953, 0.8354],
    'F1 Score': [0.7989, 0.7989, 0.7339, 0.8417],
    'ROC AUC': [0.8694, 0.8694, 0.8190, 0.9158]
})

display(results)

                 Model  Accuracy  Precision  Recall  F1 Score  ROC AUC
0  Logistic Regression    0.7899     0.7661  0.8346    0.7989   0.8694
1                  KNN    0.7899     0.7661  0.8346    0.7989   0.8694
2        Decision Tree    0.7479     0.7771  0.6953    0.7339   0.8190
3        Random Forest    0.8428     0.8480  0.8354    0.8417   0.9158

In [ ]:
metrics = ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'ROC AUC']

for metric in metrics:
    fig = px.bar(
        results,
        x='Model',
        y=metric,
        title=f'{metric} Comparison',
        labels={'Model': 'Model', metric: metric},
        color='Model',
        text_auto=True
    )
    fig.update_layout(xaxis_title='Model', yaxis_title=metric)
    fig.show()

In [ ]:
from sklearn.metrics import roc_curve, roc_auc_score
import plotly.graph_objects as go
models = {
    'Logistic Regression': best_pipeline,
    'KNN': best_knn_pipeline,
    'Decision Tree': best_dt_pipeline,
    'Random Forest': best_rf_pipeline
}

fig = go.Figure()

for name, model in models.items():
    y_proba = model.predict_proba(X_test)[:, 1]

    fpr, tpr, _ = roc_curve(y_test, y_proba)
    auc_score = roc_auc_score(y_test, y_proba)

    fig.add_trace(go.Scatter(x=fpr, y=tpr, mode='lines', name=f'{name} (AUC = {auc_score:.4f})'))

fig.add_trace(go.Scatter(x=[0, 1], y=[0, 1], mode='lines', line=dict(dash='dash'), name='Random Classifier'))

# Update layout for the plot
fig.update_layout(
    title='ROC AUC Curve Comparison',
    xaxis_title='False Positive Rate',
    yaxis_title='True Positive Rate',
    legend_title='Model',
    hovermode='x unified'
)

fig.show()

In [ ]:
preprocessor_output_features = []

# Numeric features
preprocessor_output_features.extend(num_cols)

# Categorical features
onehot_encoder = best_rf_pipeline.named_steps['preprocessor'].named_transformers_['cat'].named_steps['onehot']
onehot_feature_names = onehot_encoder.get_feature_names_out(categorical_cols)
preprocessor_output_features.extend(onehot_feature_names)

# Get feature importances from the classifier
feature_importances = best_rf_pipeline.named_steps['classifier'].feature_importances_

# Create a DataFrame for feature importances
feature_importance_df = pd.DataFrame({
    'Feature': preprocessor_output_features,
    'Importance': feature_importances
})

# Sort the features by importance
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Visualize all important features
fig = px.bar(
    feature_importance_df,
    x='Importance',
    y='Feature',
    orientation='h',
    title='Overall Feature Importance (Random Forest)',
    labels={'Importance': 'Feature Importance', 'Feature': 'Feature Name'},
    color='Importance',
    color_continuous_scale=px.colors.sequential.Viridis
)
fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

The Limit Balance and Pay_1 are the most important predictors.

**Conclusion**

▶ After performing the various model we the get the best accuracy form the Random Forest

▶ Decision Tree is the least accurate as compared to other models performed.

▶ Random Forest has the best precision and the recall balance.

▶ Higher recall can be achieved if low precision is acceptable.

▶ We can deploy the model and can be served as an aid to human decision.

▶ Model can be improved with more data and computational resources.