# 2 - Feature Engineering

In this module, we will try to create new Features which will be helpful to cluster/group the customers more efficiently.

In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.preprocessing import MinMaxScaler

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

In [2]:
from google.colab import files
uploaded = files.upload()

Saving marketing_data_clean.csv to marketing_data_clean.csv

In [4]:

df = pd.read_csv('marketing_data_clean.csv')
df.head()

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,40.900749,0.818182,95.40,0.00,95.4,0.000000,0.166667,0.000000,0.083333,0.000000,0,2,1000.0,201.802084,139.509787,0.000000,12
1,3202.467416,0.909091,0.00,0.00,0.0,6442.945483,0.000000,0.000000,0.000000,0.250000,4,0,7000.0,4103.032597,1072.340217,0.222222,12
2,2495.148862,1.000000,773.17,773.17,0.0,0.000000,1.000000,1.000000,0.000000,0.000000,0,12,7500.0,622.066742,627.284787,0.000000,12
3,1666.670542,0.636364,1499.00,1499.00,0.0,205.788017,0.083333,0.083333,0.000000,0.083333,1,1,7500.0,0.000000,864.206542,0.000000,12
4,817.714335,1.000000,16.00,16.00,0.0,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,1200.0,678.334763,244.791237,0.000000,12

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
BALANCE,8950.0,1564.474828,2081.531879,0.000000,128.281915,873.385231,2054.140036,19043.13856
BALANCE_FREQUENCY,8950.0,0.877271,0.236904,0.000000,0.888889,1.000000,1.000000,1.00000
PURCHASES,8950.0,1003.204834,2136.634782,0.000000,39.635000,361.280000,1110.130000,49039.57000
ONEOFF_PURCHASES,8950.0,592.437371,1659.887917,0.000000,0.000000,38.000000,577.405000,40761.25000
INSTALLMENTS_PURCHASES,8950.0,411.067645,904.338115,0.000000,0.000000,89.000000,468.637500,22500.00000
CASH_ADVANCE,8950.0,978.871112,2097.163877,0.000000,0.000000,0.000000,1113.821139,47137.21176
PURCHASES_FREQUENCY,8950.0,0.490351,0.401371,0.000000,0.083333,0.500000,0.916667,1.00000
ONEOFF_PURCHASES_FREQUENCY,8950.0,0.202458,0.298336,0.000000,0.000000,0.083333,0.300000,1.00000
PURCHASES_INSTALLMENTS_FREQUENCY,8950.0,0.364437,0.397448,0.000000,0.000000,0.166667,0.750000,1.00000
CASH_ADVANCE_FREQUENCY,8950.0,0.135144,0.200121,0.000000,0.000000,0.000000,0.222222,1.50000
CASH_ADVANCE_TRX,8950.0,3.248827,6.824647,0.000000,0.000000,0.000000,4.000000,123.00000
PURCHASES_TRX,8950.0,14.709832,24.857649,0.000000,1.000000,7.000000,17.000000,358.00000
CREDIT_LIMIT,8950.0,4494.449450,3638.612411,50.000000,1600.000000,3000.000000,6500.000000,30000.00000
PAYMENTS,8950.0,1733.143852,2895.063757,0.000000,383.276166,856.901546,1901.134317,50721.48336
MINIMUM_PAYMENTS,8950.0,864.206542,2330.588021,0.019163,170.857654,335.628312,864.206542,76406.20752
PRC_FULL_PAYMENT,8950.0,0.153715,0.292499,0.000000,0.000000,0.000000,0.142857,1.00000
TENURE,8950.0,11.517318,1.338331,6.000000,12.000000,12.000000,12.000000,12.00000

In [6]:
df.isnull().sum()

BALANCE                             0
BALANCE_FREQUENCY                   0
PURCHASES                           0
ONEOFF_PURCHASES                    0
INSTALLMENTS_PURCHASES              0
CASH_ADVANCE                        0
PURCHASES_FREQUENCY                 0
ONEOFF_PURCHASES_FREQUENCY          0
PURCHASES_INSTALLMENTS_FREQUENCY    0
CASH_ADVANCE_FREQUENCY              0
CASH_ADVANCE_TRX                    0
PURCHASES_TRX                       0
CREDIT_LIMIT                        0
PAYMENTS                            0
MINIMUM_PAYMENTS                    0
PRC_FULL_PAYMENT                    0
TENURE                              0
dtype: int64

In [7]:
df['BALANCE_USAGE_RATIO'] = df['BALANCE'] / df['CREDIT_LIMIT']
df['ONEOFF_PURCHASE_RATIO'] = df['ONEOFF_PURCHASES'] / (df['PURCHASES'] + 1e-6)
df['INSTALLMENT_PURCHASE_RATIO'] = df['INSTALLMENTS_PURCHASES'] / (df['PURCHASES'] + 1e-6)
df['TOTAL_PURCHASES'] = df['ONEOFF_PURCHASES'] + df['INSTALLMENTS_PURCHASES']
df['PURCHASES_PER_TRX'] = df['PURCHASES'] / df['PURCHASES_TRX']
df['CASH_ADVANCE_PER_TRX'] = df['CASH_ADVANCE'] / df['CASH_ADVANCE_TRX']
df['PAYMENT_RATIO'] = df['PAYMENTS'] / df['CREDIT_LIMIT']
df['MINIMUM_PAYMENT_RATIO'] = df['MINIMUM_PAYMENTS'] / df['CREDIT_LIMIT']
df['FULL_PAYMENT_FLAG'] = (df['PRC_FULL_PAYMENT'] == 1).astype(int)
df['UTILIZATION_RATIO'] = (df['PURCHASES'] + df['CASH_ADVANCE']) / df['CREDIT_LIMIT']

In [8]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [9]:
# Checking missing variable
df.isnull().sum().sort_values(ascending=False).head()

CASH_ADVANCE_PER_TRX      4628
PURCHASES_PER_TRX         2044
BALANCE                      0
ONEOFF_PURCHASES             0
INSTALLMENTS_PURCHASES       0
dtype: int64

In [10]:
df.fillna(0, inplace=True)

In [13]:
import os
from google.colab import files

# Saving cleaned data
os.makedirs('data', exist_ok=True)

df.to_csv("data/marketing_data_clean_w_features.csv", index=False)

print("Cleaned data is saved to 'data/marketing_data_clean_w_features.csv'")

# Download file (for Google Colab)
files.download("data/marketing_data_clean_w_features.csv")

Cleaned data is saved to 'data/marketing_data_clean_w_features.csv'